## Jeu de Sudoku

Diego et Celia

In [10]:
import random
import numpy as np

In [129]:
def MakeSudoku():
    Grid = [[0 for x in range(9)] for y in range(9)]
    
#Liste externe (for y in range(9)) - cette liste va tourner 9 fois, en creant chaque fois une nouvelle liste interne (= 9 rangées)
#Liste interne ([0 for x in range(9)]) - cette liste va determiner le contenu des liste et combien d'elements apparaissent (= 0 apparrait 9 fois pour chaque liste)
    
    for i in range(9):
        for j in range(9):
            Grid[i][j] = random.randint(1, 9)
    return Grid

# Loop externe (for i in range(9)): viens iterer sur les rangées
# Loop interne (for j in range(9)): viens iterer sur les elements de chaque rangée
# Assignation Grid[i][j] = 0 : fonctionne comme des des coordonnés [x][y] et y assigne 0
    
S = MakeSudoku()
S

[[6, 4, 7, 9, 9, 1, 9, 7, 6],
 [7, 3, 9, 4, 8, 8, 9, 5, 1],
 [1, 3, 6, 1, 7, 5, 9, 6, 3],
 [8, 6, 1, 6, 8, 2, 2, 7, 2],
 [7, 4, 2, 9, 3, 9, 9, 4, 8],
 [3, 6, 6, 2, 3, 1, 6, 3, 4],
 [8, 3, 4, 5, 9, 1, 9, 4, 7],
 [2, 8, 9, 6, 9, 6, 3, 6, 4],
 [7, 6, 9, 9, 4, 3, 1, 4, 4]]

In [104]:
m = np.array(S)
m

array([[1, 6, 5, 2, 4, 7, 9, 2, 3],
       [3, 7, 1, 8, 4, 5, 8, 1, 8],
       [4, 9, 6, 1, 1, 9, 3, 8, 5],
       [1, 4, 7, 1, 1, 2, 6, 5, 8],
       [8, 2, 6, 7, 8, 6, 9, 2, 5],
       [9, 8, 1, 9, 3, 5, 4, 6, 7],
       [1, 5, 4, 9, 9, 8, 9, 5, 4],
       [4, 4, 6, 2, 3, 6, 8, 2, 5],
       [2, 9, 9, 1, 3, 9, 5, 6, 9]])

In [105]:
digits = set(range(1, 10))
digits

{1, 2, 3, 4, 5, 6, 7, 8, 9}

In [106]:
digits.intersection([0, 0, 0])
#va retourner les chiffres qui se truvent dans le array m - donc de 1 a 9

set()

In [107]:

def alldigitsonce(l):
    'len(l) must 9.'
    
    return digits.intersection(l) == digits

In [108]:
m[1, :]

array([3, 7, 1, 8, 4, 5, 8, 1, 8])

In [109]:
m[:, 3]

array([2, 8, 1, 1, 7, 9, 9, 2, 1])

In [110]:
alldigitsonce(m[1, :])

False

In [111]:
m.shape

(9, 9)

In [112]:

def testrowsandcols(sudoku):
    n, p = sudoku.shape
    
    for i in range(n):
        if not alldigitsonce(sudoku[i, :]):
            return False
    
    for j in range(p):
        if not alldigitsonce(sudoku[:, j]):
            return False
    
    return True

In [113]:
m[0:3, 0:3]

array([[1, 6, 5],
       [3, 7, 1],
       [4, 9, 6]])

In [114]:
m[3:6, 0:3]

array([[1, 4, 7],
       [8, 2, 6],
       [9, 8, 1]])

In [115]:
m[6:9, 0:3]

array([[1, 5, 4],
       [4, 4, 6],
       [2, 9, 9]])

In [160]:

def makesq(m):
    squares = []
    for i in [0, 3, 6]:
        for j in [0, 3, 6]:
            square = m[i:(i + 3), j:(j + 3)]
            squares.append(square)
    return squares

In [133]:
minisq = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
minisq

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [134]:
minisq.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [135]:
alldigitsonce(minisq.flatten())

True

In [158]:

result = makesq(m)
for square in result:
    print(square)
    

[[1 6 5]
 [3 7 1]
 [4 9 6]]
[[2 4 7]
 [8 4 5]
 [1 1 9]]
[[9 2 3]
 [8 1 8]
 [3 8 5]]
[[1 4 7]
 [8 2 6]
 [9 8 1]]
[[1 1 2]
 [7 8 6]
 [9 3 5]]
[[6 5 8]
 [9 2 5]
 [4 6 7]]
[[1 5 4]
 [4 4 6]
 [2 9 9]]
[[9 9 8]
 [2 3 6]
 [1 3 9]]
[[9 5 4]
 [8 2 5]
 [5 6 9]]


In [152]:
result[0]

array([[1, 6, 5],
       [3, 7, 1],
       [4, 9, 6]])

In [157]:
alldigitsonce(result[0].flatten())

False

## Faire en sorte que les chiffres ne se répètent pas 

In [14]:
def is_valid_move(board, row, col, num):
    # Check if the number is not in the same row or column
    if num in board[row] or num in [board[i][col] for i in range(9)]:
        return False

    # Check if the number is not in the 3x3 subgrid
    subgrid_row, subgrid_col = 3 * (row // 3), 3 * (col // 3)
    if num in [board[subgrid_row + i][subgrid_col + j] for i in range(3) for j in range(3)]:
        return False

    return True

Fonction is_valid_move :
Cette fonction vérifie si placer un nombre dans une cellule spécifique est un mouvement valide selon les règles du Sudoku.
Elle vérifie que le nombre n'est pas déjà présent dans la même ligne, la même colonne ou le même sous-grille 3x3.

In [15]:
def solve_sudoku(board):
    empty = find_empty_location(board)
    
    # If there are no empty locations, the Sudoku is solved
    if not empty:
        return True
    
    row, col = empty

    for num in range(1, 10):
        if is_valid_move(board, row, col, num):
            # Make the move
            board[row][col] = num

            # Recursively try to solve the remaining Sudoku
            if solve_sudoku(board):
                return True

            # If the move leads to an invalid solution, backtrack
            board[row][col] = 0

    # No valid move found, backtrack
    return False

Fonction solve_sudoku :
Cette fonction utilise une approche de récursivité et de retour en arrière pour résoudre le Sudoku.
Elle trouve d'abord une cellule vide avec la fonction find_empty_location.
Ensuite, elle essaie de placer les chiffres de 1 à 9 dans cette cellule en utilisant is_valid_move.
Si un placement est valide, elle continue à résoudre le reste du Sudoku récursivement.
Si un placement conduit à une solution invalide, elle effectue une annulation (backtrack).

In [16]:
def find_empty_location(board):
    for i in range(9):
        for j in range(9):
            if board[i][j] == 0:
                return (i, j)
    return None

Fonction find_empty_location :
Cette fonction trouve la première cellule vide (contenant 0) dans le Sudoku.

In [17]:
def generate_sudoku():
    # Initialize an empty 9x9 Sudoku grid
    sudoku_grid = [[0 for _ in range(9)] for _ in range(9)]

    # Solve the Sudoku grid
    solve_sudoku(sudoku_grid)

    return sudoku_grid

# Example usage:
sudoku_board = generate_sudoku()
for row in sudoku_board:
    print(row)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[4, 5, 6, 7, 8, 9, 1, 2, 3]
[7, 8, 9, 1, 2, 3, 4, 5, 6]
[2, 1, 4, 3, 6, 5, 8, 9, 7]
[3, 6, 5, 8, 9, 7, 2, 1, 4]
[8, 9, 7, 2, 1, 4, 3, 6, 5]
[5, 3, 1, 6, 4, 2, 9, 7, 8]
[6, 4, 2, 9, 7, 8, 5, 3, 1]
[9, 7, 8, 5, 3, 1, 6, 4, 2]


Fonction generate_sudoku :
Cette fonction initialise une grille de Sudoku vide et résout cette grille en utilisant la fonction solve_sudoku.
Le résultat est une grille de Sudoku remplie qui respecte les règles du jeu.

In [20]:
 def remove_cells(board, difficulty_level):
    puzzle = [row[:] for row in board]

    if difficulty_level == "easy":
        cells_to_remove = 49
    elif difficulty_level == "difficult":
        cells_to_remove = 51
    elif difficulty_level == "challenger":
        cells_to_remove = 58
    else:
        raise ValueError("Invalid difficulty level")

    for _ in range(cells_to_remove):
        while True:
            row = random.randint(0, 8)
            col = random.randint(0, 8)
            if puzzle[row][col] != 0:
                puzzle[row][col] = 0
                break

    return puzzle

Fonction remove_cells :
Cette fonction prend une grille de Sudoku remplie (board) et un niveau de difficulté spécifié (difficulty_level : "easy", "difficult", ou "challenger").
Elle crée une copie de la grille pour éviter de modifier la grille originale.
En fonction du niveau de difficulté, elle détermine le nombre de cases à faire disparaître (cells_to_remove).
Elle utilise une boucle pour faire disparaître aléatoirement le nombre spécifié de cases, en s'assurant que chaque case n'est retirée qu'une seule fois.

In [21]:
## Exemple D'utilisation

sudoku_board = generate_sudoku()
difficulty_level = "easy"
puzzle = remove_cells(sudoku_board, difficulty_level)

for row in puzzle:
    print(row)

[0, 0, 3, 4, 5, 0, 7, 0, 0]
[0, 5, 0, 0, 0, 0, 0, 0, 0]
[0, 8, 0, 1, 0, 3, 0, 0, 0]
[0, 1, 4, 0, 0, 0, 0, 0, 7]
[3, 0, 5, 8, 9, 7, 0, 0, 4]
[8, 9, 0, 2, 0, 4, 0, 6, 0]
[0, 0, 0, 0, 4, 0, 0, 0, 0]
[0, 0, 0, 9, 0, 8, 5, 3, 1]
[9, 7, 0, 5, 0, 0, 6, 0, 0]


Exemple d'utilisation :
Générer une grille de Sudoku remplie en utilisant la fonction generate_sudoku.
Spécifier le niveau de difficulté (par exemple, "easy").
Utiliser la fonction remove_cells pour obtenir une grille de Sudoku avec le nombre spécifié de cases cachées.
Afficher la grille résultante avec les cases cachées.