## Jeu de Sudoku

Diego et Celia

In [10]:
import random
import numpy as np

In [129]:
def MakeSudoku():
    Grid = [[0 for x in range(9)] for y in range(9)]
    
#Liste externe (for y in range(9)) - cette liste va tourner 9 fois, en creant chaque fois une nouvelle liste interne (= 9 rangées)
#Liste interne ([0 for x in range(9)]) - cette liste va determiner le contenu des liste et combien d'elements apparaissent (= 0 apparrait 9 fois pour chaque liste)
    
    for i in range(9):
        for j in range(9):
            Grid[i][j] = random.randint(1, 9)
    return Grid

# Loop externe (for i in range(9)): viens iterer sur les rangées
# Loop interne (for j in range(9)): viens iterer sur les elements de chaque rangée
# Assignation Grid[i][j] = 0 : fonctionne comme des des coordonnés [x][y] et y assigne 0
    
S = MakeSudoku()
S

[[6, 4, 7, 9, 9, 1, 9, 7, 6],
 [7, 3, 9, 4, 8, 8, 9, 5, 1],
 [1, 3, 6, 1, 7, 5, 9, 6, 3],
 [8, 6, 1, 6, 8, 2, 2, 7, 2],
 [7, 4, 2, 9, 3, 9, 9, 4, 8],
 [3, 6, 6, 2, 3, 1, 6, 3, 4],
 [8, 3, 4, 5, 9, 1, 9, 4, 7],
 [2, 8, 9, 6, 9, 6, 3, 6, 4],
 [7, 6, 9, 9, 4, 3, 1, 4, 4]]

In [104]:
m = np.array(S)
m

array([[1, 6, 5, 2, 4, 7, 9, 2, 3],
       [3, 7, 1, 8, 4, 5, 8, 1, 8],
       [4, 9, 6, 1, 1, 9, 3, 8, 5],
       [1, 4, 7, 1, 1, 2, 6, 5, 8],
       [8, 2, 6, 7, 8, 6, 9, 2, 5],
       [9, 8, 1, 9, 3, 5, 4, 6, 7],
       [1, 5, 4, 9, 9, 8, 9, 5, 4],
       [4, 4, 6, 2, 3, 6, 8, 2, 5],
       [2, 9, 9, 1, 3, 9, 5, 6, 9]])

In [105]:
digits = set(range(1, 10))
digits

{1, 2, 3, 4, 5, 6, 7, 8, 9}

In [106]:
digits.intersection([0, 0, 0])
#va retourner les chiffres qui se truvent dans le array m - donc de 1 a 9

set()

In [107]:
def alldigitsonce(l):
    'len(l) must 9.'
    
    return digits.intersection(l) == digits

In [108]:
m[1, :]

array([3, 7, 1, 8, 4, 5, 8, 1, 8])

In [109]:
m[:, 3]

array([2, 8, 1, 1, 7, 9, 9, 2, 1])

In [110]:
alldigitsonce(m[1, :])

False

In [111]:
m.shape

(9, 9)

In [112]:
def testrowsandcols(sudoku):
    n, p = sudoku.shape
    
    for i in range(n):
        if not alldigitsonce(sudoku[i, :]):
            return False
    
    for j in range(p):
        if not alldigitsonce(sudoku[:, j]):
            return False
    
    return True

In [113]:
m[0:3, 0:3]

array([[1, 6, 5],
       [3, 7, 1],
       [4, 9, 6]])

In [114]:
m[3:6, 0:3]

array([[1, 4, 7],
       [8, 2, 6],
       [9, 8, 1]])

In [115]:
m[6:9, 0:3]

array([[1, 5, 4],
       [4, 4, 6],
       [2, 9, 9]])

In [160]:
def makesq(m):
    squares = []
    for i in [0, 3, 6]:
        for j in [0, 3, 6]:
            square = m[i:(i + 3), j:(j + 3)]
            squares.append(square)
    return squares

In [133]:
minisq = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
minisq

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [134]:
minisq.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [135]:
alldigitsonce(minisq.flatten())

True

In [158]:
result = makesq(m)
for square in result:
    print(square)
    

[[1 6 5]
 [3 7 1]
 [4 9 6]]
[[2 4 7]
 [8 4 5]
 [1 1 9]]
[[9 2 3]
 [8 1 8]
 [3 8 5]]
[[1 4 7]
 [8 2 6]
 [9 8 1]]
[[1 1 2]
 [7 8 6]
 [9 3 5]]
[[6 5 8]
 [9 2 5]
 [4 6 7]]
[[1 5 4]
 [4 4 6]
 [2 9 9]]
[[9 9 8]
 [2 3 6]
 [1 3 9]]
[[9 5 4]
 [8 2 5]
 [5 6 9]]


In [152]:
result[0]

array([[1, 6, 5],
       [3, 7, 1],
       [4, 9, 6]])

In [157]:
alldigitsonce(result[0].flatten())

False