## Jeu de Sudoku

Diego et Celia

In [10]:
import random
import numpy as np

In [9]:
def MakeSudoku():
    Grid = [[0 for x in range(9)] for y in range(9)]
    
#Liste externe (for y in range(9)) - cette liste va tourner 9 fois, en creant chaque fois une nouvelle liste interne (= 9 rangées)
#Liste interne ([0 for x in range(9)]) - cette liste va determiner le contenu des liste et combien d'elements apparaissent (= 0 apparrait 9 fois pour chaque liste)
    
    for i in range(9):
        for j in range(9):
            Grid[i][j] = 0
    return Grid

# Loop externe (for i in range(9)): viens iterer sur les rangées
# Loop interne (for j in range(9)): viens iterer sur les elements de chaque rangée
# Assignation Grid[i][j] = 0 : fonctionne comme des des coordonnés [x][y] et y assigne 0
    
m = MakeSudoku()

In [13]:
m = np.array(m)

In [15]:
digits = set(range(1, 10))
digits

{1, 2, 3, 4, 5, 6, 7, 8, 9}

In [17]:
digits.intersection([0, 0, 0])

set()

In [27]:
def alldigitsonce(l):
    'len(l) must 9.'
    
    return digits.intersection(l) == digits

In [29]:
m[1, :]

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [30]:
m[:, 3]

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [28]:
alldigitsonce(m[1, :])

False

In [31]:
m.shape

(9, 9)

In [ ]:
def testrowsandcols(sudoku):
    n, p = sudoku.shape
    
    for i in range(n):
        if not alldigitsonce(sudoku[i, :]):
            return False
    
    for j in range(p):
        if not alldigitsonce(sudoku[:, j]):
            return False
    
    return True

In [38]:
v = np.arange(105, 115)

In [39]:
v

array([105, 106, 107, 108, 109, 110, 111, 112, 113, 114])

In [40]:
v[3:6]

array([108, 109, 110])

In [42]:
m[0:3, 0:3]

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [43]:
m[3:6, 0:3]

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [44]:
m[6:9, 0:3]

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [45]:
for i in [0, 3, 6]:
    for j in [0, 3, 6]:
        m[i:(i + 3), j:(j + 3)]

In [50]:
minisq = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
minisq

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
minisq.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
alldigitsonce(minisq.flatten())

True